title: The F* Five!
email: hotdq+dnd@cle.ar.it
description: >- # this means to ignore newlines until "baseurl:"
  Checking out some dragons. And those undead over there.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hotdq.dndaux.de" # the base hostname & protocol for your site, e.g. http://example.comemail:              your-email@example.com
author: m_sc

# Social Profiles
twitter_username: Wayneoween
github_username: Wayneoween

#remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

  # https://codepen.io/yoannhel/pen/sJpDj
  # This needs to be done! :-)